// WATS-53/WATS-65 public message-template endpoint subpath.
//
// Thin compatibility barrel over the WATS-65 template endpoint family modules.

export {
  buildCreateMessageTemplateBody,
  buildUpdateMessageTemplateBody,
  buildTemplateBodyComponent,
  buildTemplateButtonComponent,
  buildTemplateFooterComponent,
  buildTemplateHeaderComponent,
  createMessageTemplate,
  createTemplateGroup,
  compareTemplates,
  migrateTemplates,
  archiveTemplates,
  unarchiveTemplates,
  upsertAuthenticationTemplate,
  buildUpsertAuthenticationTemplateBody,
  deleteMessageTemplate,
  deleteTemplateGroup,
  getMessageTemplate,
  getTemplateGroup,
  getTemplateGroupAnalytics,
  listMessageTemplates,
  listTemplateGroups,
  unpauseTemplate,
  updateMessageTemplate,
  updateTemplateGroup,
  validateTemplateParameterCounts,
  ARCHIVE_TEMPLATES_MAX_IDS,
  COMPARE_TEMPLATES_MAX_IDS,
  UPSERT_AUTH_LANGUAGES_MAX,
  UPSERT_AUTH_SUPPORTED_APPS_MAX,
  KNOWN_TEMPLATE_TOP_BLOCK_REASONS,
  KNOWN_UPSERT_AUTH_OTP_TYPES
} from "./templates/index.js";

export type {
  CreateMessageTemplateBody,
  CreateTemplateGroupBody,
  DeleteMessageTemplateInput,
  DeleteTemplateGroupInput,
  GetMessageTemplateInput,
  GetTemplateGroupInput,
  GraphPaging,
  ListMessageTemplatesInput,
  ListTemplateGroupsInput,
  SendTemplateComponentForValidation,
  TemplateBodyComponentInput,
  TemplateButtonInput,
  TemplateButtonsComponentInput,
  TemplateButtonType,
  TemplateCategory,
  TemplateComponent,
  TemplateDefinitionForValidation,
  TemplateDetails,
  TemplateGroupAnalyticsInput,
  TemplateGroupAnalyticsPoint,
  TemplateGroupAnalyticsResponse,
  TemplateGroupBody,
  TemplateGroupDetails,
  TemplateGroupListResponse,
  TemplateGroupMutationResponse,
  TemplateFooterComponentInput,
  TemplateHeaderComponentInput,
  TemplateHeaderFormat,
  TemplateLanguageCode,
  TemplateListResponse,
  TemplateMutationResponse,
  TemplateParameterFormat,
  TemplateQualityScore,
  TemplateStatus,
  UpdateMessageTemplateBody,
  UpdateTemplateGroupBody
} from "./templates/index.js";

export type {
  ArchiveTemplatesInput,
  ArchiveTemplatesResponse,
  CompareTemplatesInput,
  FailedTemplateEntry,
  MigrateTemplatesInput,
  MigrateTemplatesResponse,
  MigratedTemplateEntry,
  TemplateTopBlockReason,
  TemplateUnpauseResult,
  TemplatesCompareResult,
  UnarchiveTemplatesInput,
  UnarchiveTemplatesResponse,
  UnpauseTemplateInput,
  UpsertAuthOtpButtonInput,
  UpsertAuthOtpType,
  UpsertAuthSupportedAppInput,
  UpsertAuthenticationTemplateBody,
  UpsertAuthenticationTemplateResponse,
  UpsertedAuthTemplateEntry
} from "./templates/index.js";
