// F-7/WATS-39 WABA-scope endpoints.
//
// WATS-39 adds credential-free WhatsApp Business Account message-template
// management parity. All operations are ordinary Graph endpoint callables
// layered on defineEndpoint and MockTransport-testable without live WABA
// credentials.

export { listPhoneNumbers } from "./waba/index.js";

export type {
  GraphPaging,
  PhoneNumberListEntry,
  PhoneNumberListResponse
} from "./waba/index.js";

export {
  buildCreateMessageTemplateBody,
  buildUpdateMessageTemplateBody,
  buildTemplateBodyComponent,
  buildTemplateButtonComponent,
  buildTemplateFooterComponent,
  buildTemplateHeaderComponent,
  createMessageTemplate,
  deleteMessageTemplate,
  getMessageTemplate,
  listMessageTemplates,
  updateMessageTemplate,
  listTemplateGroups,
  createTemplateGroup,
  getTemplateGroup,
  updateTemplateGroup,
  deleteTemplateGroup,
  getTemplateGroupAnalytics,
  compareTemplates,
  unpauseTemplate,
  COMPARE_TEMPLATES_MAX_IDS,
  KNOWN_TEMPLATE_TOP_BLOCK_REASONS,
  validateTemplateParameterCounts
} from "./templates/index.js";

export type {
  CreateMessageTemplateBody,
  DeleteMessageTemplateInput,
  GetMessageTemplateInput,
  ListMessageTemplatesInput,
  ListTemplateGroupsInput,
  SendTemplateComponentForValidation,
  TemplateBodyComponentInput,
  TemplateButtonInput,
  TemplateButtonsComponentInput,
  TemplateButtonType,
  TemplateCategory,
  TemplateComponent,
  TemplateDefinitionForValidation,
  TemplateDetails,
  TemplateGroupAnalyticsInput,
  TemplateGroupAnalyticsPoint,
  TemplateGroupAnalyticsResponse,
  TemplateGroupBody,
  TemplateGroupDetails,
  TemplateGroupListResponse,
  TemplateGroupMutationResponse,
  TemplateFooterComponentInput,
  TemplateHeaderComponentInput,
  TemplateHeaderFormat,
  TemplateLanguageCode,
  TemplateListResponse,
  TemplateMutationResponse,
  TemplateOtpType,
  TemplateParameterFormat,
  TemplateQualityScore,
  TemplateStatus,
  TemplateSupportedAppInput,
  UpdateMessageTemplateBody,
  CreateTemplateGroupBody,
  DeleteTemplateGroupInput,
  GetTemplateGroupInput,
  UpdateTemplateGroupBody,
  CompareTemplatesInput,
  TemplateTopBlockReason,
  TemplateUnpauseResult,
  TemplatesCompareResult,
  UnpauseTemplateInput
} from "./templates/index.js";


// ---------------------------------------------------------------------------
// WATS-40 WhatsApp Flows endpoint parity.
// ---------------------------------------------------------------------------
/**
 * @experimental Flow DSL and data-channel helpers may change in 0.x minors while WATS expands Flow parity.
 */

export {
  FLOW_DSL_MAX_CONTROL_DEPTH,
  FLOW_JSON_MAX_ARRAY_LENGTH,
  FLOW_JSON_MAX_BYTES,
  FLOW_JSON_MAX_COMPONENTS,
  FLOW_JSON_MAX_DEPTH,
  FLOW_JSON_MAX_SCREENS,
  FLOW_JSON_MAX_STRING_LENGTH,
  FLOW_MAX_CATEGORIES,
  KNOWN_FLOW_METRIC_GRANULARITIES,
  KNOWN_FLOW_METRIC_NAMES,
  MIGRATE_FLOWS_MAX_NAMES,
  MIGRATE_FLOWS_NAME_MAX_LENGTH,
  buildFlowCloseResponse,
  buildFlowErrorResponse,
  buildFlowJson,
  buildFlowMetricField,
  buildFlowScreenResponse,
  calendarPicker,
  checkboxGroup,
  chipsSelector,
  completeAction,
  createFlow,
  dataExchangeAction,
  dataSource,
  datePicker,
  deleteFlow,
  deprecateFlow,
  documentPicker,
  dropdown,
  embeddedLink,
  flowJson,
  footer,
  form,
  getFlow,
  getFlowAssets,
  getFlowMetrics,
  ifComponent,
  image,
  imageCarousel,
  imageCarouselItem,
  listFlows,
  migrateFlows,
  navigateAction,
  navigationItem,
  navigationList,
  openUrlAction,
  optIn,
  photoPicker,
  publishFlow,
  radioButtonsGroup,
  richText,
  screen,
  singleColumnLayout,
  switchComponent,
  textArea,
  textBody,
  textCaption,
  textHeading,
  textInput,
  textSubheading,
  updateDataAction,
  updateFlowJson,
  updateFlowMetadata,
  validateFlowJson
} from "./flows/index.js";

export type {
  CreateFlowBody,
  FlowAssetDetails,
  FlowAssetsResponse,
  FlowCategory,
  FlowCloseResponse,
  FlowCloseResponseInput,
  FlowDetails,
  FlowErrorResponse,
  FlowErrorResponseInput,
  FlowJson,
  FlowJsonProps,
  FlowListResponse,
  FlowMetric,
  FlowMetricDataPoint,
  FlowMetricGranularity,
  FlowMetricName,
  FlowMutationResponse,
  FlowScreenResponse,
  FlowScreenResponseInput,
  FlowStatus,
  FormProps,
  GetFlowAssetsInput,
  GetFlowInput,
  GetFlowMetricsInput,
  IfProps,
  ImageCarouselItemProps,
  ListFlowsInput,
  MigratedFlow,
  MigratedFlowError,
  MigrateFlowsInput,
  MigrateFlowsResponse,
  NavigateActionProps,
  NavigationItemProps,
  ScreenProps,
  SwitchProps,
  UpdateFlowJsonBody,
  UpdateFlowMetadataBody
} from "./flows/index.js";
