import { createFileRoute } from "@tanstack/react-router"
import { FeatureCard } from "../components/FeatureCard"
import { SiteFooter } from "../components/SiteFooter"
import { SiteNav } from "../components/SiteNav"
import { TerminalPanel } from "../components/TerminalPanel"
import { TrustStrip } from "../components/TrustStrip"
import { testCountRounded } from "../lib/meta"
import heroSource from "../../snippets/hero.ts?raw"
import heroCaptured from "../generated/hero-captured.json"

// Landing page. Copy is governed by VOICE.md; numeric/capability claims stay
// generated-or-true.

export const Route = createFileRoute("/")({
  head: () => ({
    links: [{ rel: "canonical", href: "https://wats.sh" }],
  }),
  component: Home,
})

const linkFocus =
  "transition-colors duration-150 focus-visible:outline-2 focus-visible:outline-accent"

// Hero snippet: real source from snippets/hero.ts (typechecked against
// published @wats/* by `bun run typecheck:snippets`); captured request
// generated by scripts/gen-hero-capture.ts actually running it.
const HERO_SNIPPET = heroSource.trimEnd()
const CAPTURED_REQUEST = JSON.stringify(heroCaptured, null, 2)

// TEST_COUNT is generated by scripts/gen-meta.ts (real `bun test` output,
// refreshed per release) and consumed via src/lib/meta.ts — never hand-written.
const TRUST_ITEMS = [
  `${testCountRounded}+ tests passing`,
  "0 hard dependencies",
  "Bun-first",
  "MIT",
]

function Hero() {
  return (
    <section className="grid items-center gap-10 md:grid-cols-2">
      <div className="space-y-6">
        <h1 className="text-4xl font-semibold leading-tight text-text md:text-5xl">
          The WhatsApp Cloud API, typed end to end.
        </h1>
        <p className="text-lg leading-relaxed text-text-muted">
          Composable TypeScript packages for bots, webhooks, and the Graph API.
          Run the whole SDK in your browser — no credentials, no install, no
          network.
        </p>
        <div className="flex flex-wrap items-center gap-4">
          <a
            href="/playground"
            className={`rounded bg-accent px-4 py-2 font-semibold text-bg hover:bg-accent-dim ${linkFocus}`}
          >
            Open the playground →
          </a>
          <a
            href="/docs/quickstart"
            className={`rounded border border-border px-4 py-2 text-text hover:border-accent-dim ${linkFocus}`}
          >
            Quickstart →
          </a>
        </div>
        <p>
          <a
            href="/docs/parity"
            className={`mono text-sm text-text-muted hover:text-text ${linkFocus}`}
          >
            alpha · endpoint status →
          </a>
        </p>
      </div>
      {/* min-w-0 lets the code panel's horizontal scroll work inside the grid
          track instead of overflowing the rounded panel edge. */}
      <div className="min-w-0">
        <TerminalPanel
          tabs={[
            {
              label: "bot.ts",
              content: (
                <pre className="mono overflow-x-auto text-sm leading-relaxed text-text-muted">
                  <code>{HERO_SNIPPET}</code>
                </pre>
              ),
            },
            {
              label: "captured request",
              content: (
                <pre className="mono overflow-x-auto text-sm leading-relaxed text-text-muted">
                  <code>{CAPTURED_REQUEST}</code>
                </pre>
              ),
            },
          ]}
        />
      </div>
    </section>
  )
}

function FeatureCards() {
  return (
    <section className="grid gap-4 md:grid-cols-3">
      <FeatureCard
        title="Typed end to end"
        body="Discriminated unions for every message and webhook shape. Narrow Meta errors with instanceof, not string matching. Construction-time validation catches bad payloads before the wire."
        href="/docs/reference/errors"
      />
      <FeatureCard
        title="Webhook runtime included"
        body="Signature verification, envelope normalization, a typed router with filters and listeners. One facade from inbound event to typed handler."
        href="/docs/reference/webhook-normalizer"
      />
      <FeatureCard
        title="Groups API"
        body="Create groups, manage participants, send to groups — same typed client as everything else."
        href="/docs/reference/groups"
      />
    </section>
  )
}

function WireSection() {
  return (
    <section className="space-y-4 rounded-lg border border-border bg-bg-raised p-8">
      <h2 className="text-2xl font-semibold text-text md:text-3xl">
        See exactly what hits the wire. Before anything does.
      </h2>
      <p className="max-w-3xl leading-relaxed text-text-muted">
        Every WATS client runs against a Transport seam. Swap in MockTransport
        and the SDK captures the exact Graph request — method, path, payload —
        without a network in sight. Develop a complete bot before you have
        credentials.
      </p>
      <p>
        <a
          href="/playground"
          className={`font-semibold text-accent hover:text-text ${linkFocus}`}
        >
          Run it yourself →
        </a>
      </p>
    </section>
  )
}

function StatusSection() {
  return (
    <section className="space-y-4">
      <h2 className="text-2xl font-semibold text-text md:text-3xl">
        Alpha, in the useful sense.
      </h2>
      <p className="max-w-3xl leading-relaxed text-text-muted">
        The core paths — sending, webhooks, templates, errors — are tested and
        have carried real traffic. The wider endpoint surface is typed and
        tested against the wire contract. The parity page tracks the status of
        each endpoint, so you can check yours before you build on it.
      </p>
      <p>
        <a
          href="/docs/parity"
          className={`font-semibold text-accent hover:text-text ${linkFocus}`}
        >
          Endpoint status →
        </a>
      </p>
    </section>
  )
}

function Home() {
  return (
    <div className="min-h-screen bg-bg text-text">
      <SiteNav />
      {/* Vertical rhythm per 03-design.md §4: 96px desktop / 56px mobile. */}
      <main className="mx-auto max-w-[1152px] space-y-14 px-6 py-14 md:space-y-24 md:py-24">
        <Hero />
        <TrustStrip items={TRUST_ITEMS} />
        <FeatureCards />
        <WireSection />
        <StatusSection />
      </main>
      <SiteFooter />
    </div>
  )
}
