import { mkdir, rm, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(repoRoot, "docs", "api");

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const symbols = [
  { name: "@switchbord/types", entry: "packages/types/src/index.ts" },
  { name: "@switchbord/crypto", entry: "packages/crypto/src/index.ts" },
  { name: "@switchbord/graph", entry: "packages/graph/src/index.ts" },
  { name: "@switchbord/core", entry: "packages/core/src/index.ts" },
  { name: "@switchbord/http", entry: "packages/http/src/index.ts" },
  { name: "@switchbord/internal-utils", entry: "packages/internal-utils/src/index.ts" },
  { name: "@switchbord/config", entry: "packages/config/src/index.ts" },
  { name: "@switchbord/service", entry: "packages/service/src/index.ts" },
  { name: "@switchbord/cli", entry: "packages/cli/src/index.ts" }
];

const content = `# Package API

- status: generated-stub
- applies-to: WATS-36A
- lastReviewed: 2026-05-01

This page is generated by \`bun run docs:api\` as the WATS-36A TypeDoc-ready API entry point. It documents the alpha package entry files, including \`@switchbord/internal-utils\` as published internal support for public runtime packages, and excludes private workspace packages such as \`@switchbord/testing\`.

A later WATS-36B pass can swap this stub generator for full \`typedoc --options typedoc.json\` output once TypeDoc/TypeScript peer support is pinned for the release line.

| Package | Entry point |
| --- | --- |
${symbols.map((s) => `| \`${s.name}\` | \`${s.entry}\` |`).join("\n")}
`;

await writeFile(join(outDir, "index.md"), content, "utf8");
console.log(`generated ${join(outDir, "index.md")}`);
